### ISSUE TITLE
Semantic elements

### ISSUE THREAD

**Issue by cjessett** [Wynforth33/Dasmoto-Project-CA-#1]
(Subtlety) Instead of using `div` for different sections and your header, use the semantic elements [`section`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) and [`header`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) respectively. These are block elements just like `div`'s only they improve the readability of our code.

**Comment by Wynforth33** [comment]
Modified the 'div' tags so that the banner 'div' is now 'header'; and, each of the 'div class=section' is now just 'section'.
