### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by cjessett** [Wynforth33/Dasmoto-Project-CA-#3]
(Simplify) [This `section` css class](https://github.com/Wynforth33/prj-rev-bwfs-dasmoto/blob/2aaa10334367ba456df4d9e4c7db4704015d8351/Dasmoto/index.html#L13) is not necessary since you don't apply styles to it, just omit it.

**Comment by Wynforth33** [comment]
Fixed by using <section> rather than <div class="section"> it also lowers specificity so i can keep the option to use section later without the class.. should have gone back through the tag guide provided.
